### PR TITLE
A shorter version, which uses set()

### PR DESCRIPTION
**Pull request by vsg**

### CODE REVIEW

**Comment by vsg** [comment]
The same thing could be done to advent_3_2.py

**Comment by harisphnx** [comment]
Thanx, You can change the code for advent_3_2.py, so that I can merge. Same for Day 2.

**Comment by vsg** [comment]
> Thanx, You can change the code for advent_3_2.py, so that I can merge. Same for Day 2.

The purpose of adventofcode is for everybody to learn something new (e.g. I didn't know there's string.count() method), so I'll leave that for you to practice. Have fun!

**Comment by harisphnx** [comment]
Actually, I think it cannot be done for advent_3_2.py, because I am using a list to store position of both santa and the robot. It is easier that way and makes the code smaller(I think so, may be there is another way), and list are immutable and thus cannot be used as they are not hashable.

**Comment by vsg** [comment]
> Actually, I think it cannot be done for advent_3_2.py, because I am using a list to store position of both santa and the robot.

A set can contain anything immutable. Currently you have immutable strings, and you could put those into a set:

``` Python
    hash_set = set(["" + str(x[bit]) + "," + str(y[bit])])
    ...
    hash_set.add("" + str(x[bit]) + "," + str(y[bit]))
```

You could improve that by using string formatting, which would avoid string concatenations, like so:

``` Python
    hash_set = set(["%i,%i" % (x[bit], y[bit])])
    ...
    hash_set.add("%i,%i" % (x[bit], y[bit]))
```

But also you could remove (number -> string) conversions by using tuples, which unlike lists are immutable and can be stored into a set:

``` Python
    hash_set = set([ tuple(x[bit], y[bit]) ])
    ...
    hash_set.add( tuple(x[bit], y[bit]) )
```

Or even shorter, yet still familiar to any experienced python user, by using tuple literals:

``` Python
    hash_set = set([ (x[bit], y[bit]) ])
    ...
    hash_set.add( (x[bit], y[bit]) )
```

**Pull request merged**
